language: python
sudo: true

python:
    - "2.7"
    - "3.6"

addons:
  apt:
    packages:
      - swig
      - softhsm

before_install:
    - sudo chmod -R a+rx /etc/softhsm
    - sudo chown -R $(whoami) /var/lib/softhsm
    - sudo sed -i 's/lib\/lib/lib/' /etc/softhsm/softhsm.conf
    - touch /var/lib/softhsm/slot0.db

install:
    - pip install -r dev-requirements.txt
    - pip install .
    - softhsm --init-token --slot 0 --label "A token" --pin 1234 --so-pin 123456

script:
    - make prepare4test
    - ./run_test.py
    - coverage run run_test.py

after_success:
    - coveralls
